### ISSUE TITLE
is blosc2 supporting 64bit buffer?

### ISSUE THREAD

**Issue by psychocoderHPC** [Blosc/c-blosc2#72]
In `blosc` we ask for 64bit buffer support https://github.com/Blosc/c-blosc/issues/67 and  @FrancescAlted pointed out that it will be supported in `blosc2`. Is this the case or do we still have the 32bit limitation?

**Comment by FrancescAlted** [comment]
Yes, 64-bit buffer support is here, but you have to use a chunked approach in order to fill the compressed buffer.  For this, you need to attach a super-chunk to a frame, fill it, and at the end you will get the final sequential container.  See an example in https://github.com/Blosc/c-blosc2/blob/master/examples/frame_backed_schunk.c.
